#!/bin/bash 

sed -i "s/AC\$CHROMATOGRAPHY: SOLVENT CH3OH(0.1%TFA)\/ H2O(0.1%TFA)/AC\$CHROMATOGRAPHY: SOLVENT A CH3OH(0.1%TFA)\nAC\$CHROMATOGRAPHY: SOLVENT B H2O(0.1%TFA)/" *.txt

sed -i "s/AC\$CHROMATOGRAPHY: SOLVENT CH3CN(0.1%TFA)\/ H2O(0.1%TFA)/AC\$CHROMATOGRAPHY: SOLVENT A CH3CN(0.1%TFA)\nAC\$CHROMATOGRAPHY: SOLVENT B H2O(0.1%TFA)/" *.txt

sed -i "s/AC\$CHROMATOGRAPHY: SOLVENT CH3CN(0.05% HCOOH) \/ HCOOH(0.05% CH3CN)/AC\$CHROMATOGRAPHY: SOLVENT A CH3CN(0.05% HCOOH)\nAC\$CHROMATOGRAPHY: SOLVENT B HCOOH(0.05% CH3CN)/" *.txt
