language: java
install: 
  - git clone -q https://github.com/MassBank/MassBank-web.git .scripts/MassBank-web
  - ( cd .scripts/MassBank-web ; git checkout 0e47e5ec20918b7d41583e4e907a7eb1eb0878d8 )
  - mvn -q -f .scripts/MassBank-web/MassBank-Project/MassBank-lib/pom.xml install
  - tar -xvjf .scripts/libinchi.tar.bz -C ~
script: 
  - bash .scripts/validate.sh $TESTDIR
env:
 - TESTDIR=Athens_Univ/
 - TESTDIR=Boise_State_Univ/
 - TESTDIR=BS/
 - TESTDIR=CASMI_2012/
 - TESTDIR=CASMI_2016/
 - TESTDIR=Chubu_Univ/
 - TESTDIR=Eawag/
 - TESTDIR=Eawag_Additional_Specs/
 - TESTDIR=Env_Anal_Chem_U_Tuebingen/
 - TESTDIR=Fac_Eng_Univ_Tokyo/
 - TESTDIR=Fiocruz/
 - TESTDIR=Fukuyama_Univ/
 - TESTDIR=GL_Sciences_Inc/
 - TESTDIR=IPB_Halle/
 - TESTDIR=JEOL_Ltd/
 - TESTDIR=Kazusa/
 - TESTDIR=Keio_Univ/
 - TESTDIR=Kyoto_Univ/
 - TESTDIR=Literature_Specs/
 - TESTDIR=MetaboLights/
 - TESTDIR=Metabolon/
 - TESTDIR=MPI_for_Chemical_Ecology/
 - TESTDIR=MSSJ/
 - TESTDIR=NAIST/
 - TESTDIR=Nihon_Univ/
 - TESTDIR=Osaka_MCHRI/
 - TESTDIR=Osaka_Univ/
 - TESTDIR=PFOS_research_group/
 - TESTDIR=RIKEN/
 - TESTDIR=Tottori_Univ/
 - TESTDIR=UFZ/
 - TESTDIR=UFZ_Additional_Specs/
 - TESTDIR=Univ_Connecticut/
 - TESTDIR=Univ_Toyama/
 - TESTDIR=UOEH/
 - TESTDIR=UPAO/
 - TESTDIR=Washington_State_Univ/
 - TESTDIR=Waters/
