#!/bin/bash

cat << 'EOF' > .travis.yml
language: java
dist: xenial
cache:
  directories:
  - $HOME/.m2
install:
  - if [ -z "$TRAVIS_TAG" ]; then git clone --branch $TRAVIS_BRANCH --depth 1 -q https://github.com/MassBank/MassBank-web.git .scripts/MassBank-web; else git clone --depth 1 -q https://github.com/MassBank/MassBank-web.git .scripts/MassBank-web; fi
  - mvn -q -f .scripts/MassBank-web/MassBank-Project/MassBank-lib/pom.xml install
  - tar -xjf .scripts/libinchi.tar.bz -C ~
script: 
  - .scripts/validate.sh $TESTDIR
env:
EOF
for x in $(ls -d */)
do
 if [ "$x" = ".scripts/" ]; then
  continue
 fi
 if [ "$x" = "figure/" ]; then
  continue
 fi
 echo " - TESTDIR=$x" >> .travis.yml
done
# readd .travis.yml after change
git add .travis.yml
