#!/bin/bash

cat << 'EOF' > .travis.yml
language: java
install: 
  - git clone --depth 1 -q https://github.com/MassBank/MassBank-web.git .scripts/MassBank-web
  - mvn -q -f .scripts/MassBank-web/MassBank-Project/MassBank-lib/pom.xml install
  - tar -xvjf .scripts/libinchi.tar.bz -C ~
script: 
  - bash .scripts/validate.sh $TESTDIR
env:
EOF
for x in $(ls -d */)
do
 if [ "$x" = ".scripts/" ]; then
  continue
 fi
 echo " - TESTDIR=$x" >> .travis.yml
done
# readd .travis.yml after change
git add .travis.yml
