sed 's|ANALYTICAL_CONDITION: MODE NEGATIVE|MASS_SPECTROMETRY: ION_MODE NEGATIVE|g' -i *

sed 's|ANALYTICAL_CONDITION: MODE POSITIVE|MASS_SPECTROMETRY: ION_MODE POSITIVE|g' -i *


sed '/STRUCTURE_FILE_NAME/d' -i *

sed 's|ANALYTICAL_CONDITION: IONIZATION ESI|MASS_SPECTROMETRY: IONIZATION ESI|g' -i *

sed 's|ANALYTICAL_CONDITION: CAPILLARY_VOLTAGE|MASS_SPECTROMETRY: CAPILLARY_VOLTAGE|g' -i *

sed 's|ANALYTICAL_CONDITION: MS_TYPE LC-MS2/MS|MASS_SPECTROMETRY: MS_TYPE MS2|g' -i *

sed 's|ANALYTICAL_CONDITION: COLLISION_ENERGY|MASS_SPECTROMETRY: COLLISION_ENERGY|g' -i *

sed 's|ANALYTICAL_CONDITION: SOLVENT|CHROMATOGRAPHY: SOLVENT|g' -i *

sed 's|ANALYTICAL_CONDITION: FRAGMENTATION_METHOD|MASS_SPECTROMETRY: FRAGMENTATION_MODE|g' -i *

sed 's|ANALYTICAL_CONDITION: SOURCE_TEMPERATURE|MASS_SPECTROMETRY: SOURCE_TEMPERATURE|g' -i *

sed 's|ANALYTICAL_CONDITION: SAMPLING_CONE|CHROMATOGRAPHY: SAMPLING_CONE|g' -i *

sed 's|    |  |g' -i *

sed 's|InChI=1/|InChI=1S/|g'  -i *

sed '/ANALYTICAL_CONDITION: PRECURSOR_SELECTION/d' -i *

sed '/ANALYTICAL_CONDITION: FRAGMENTATION_EQUIPMENT/d' -i *

sed '/ANALYTICAL_CONDITION: SPECTRUM_TYPE/d' -i *

sed '/ANALYTICAL_CONDITION: DATAFORMAT/d' -i *



