name: Add to Records and Create Pull Request

on:
  push:
    branches:
      - check-chemont

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  update-records:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout this repo's code
        uses: actions/checkout@v4
        with:
          path: MassBank-data

      - name: Checkout MassBank ClassyFire repository
        uses: actions/checkout@v4
        if: ${{ (github.ref != 'refs/heads/main') && (github.base_ref != 'main') }}
        with:
          repository: michaelwenk/MassBank-ClassyFire
          path: MassBank-ClassyFire
          fetch-depth: 1
          ref: main

      - name: Run script to modify the MassBank records
        # working-directory: MassBank-ClassyFire
        run: |
          echo "Running script to modify the MassBank records..."
          #   echo "--> 1"
          #   find . -name "MSBNK-*.txt"

          #   echo "current dir"
          #   ls -a
          #   echo "parent dir"
          #   ls -a ..

          pip install -r MassBank-ClassyFire/requirements.txt

          echo "test first script"
          python MassBank-ClassyFire/create_query_list.py MassBank-data
          echo "test second script"
          ls MassBank-ClassyFire
          ls -a 
          ls MassBank-ClassyFire/results
          echo "head:"
          head MassBank-ClassyFire/results/query_list.tsv
          echo "tail:"
          tail MassBank-ClassyFire/results/query_list.tsv

          echo "DONE!!!"

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "Changes detected."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

    #   # Commit and Push Changes if there are any
    #   - name: Commit and Create Pull Request
    #     if: steps.check_changes.outputs.has_changes == 'true'
    #     run: |
    #       # configure user
    #       git config --global user.name "${{ github.actor }}"
    #       git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    #       # create branch name variable
    #       branch="update-version-pull-request"

    #       # create a new branch for the changes
    #       git checkout -b $branch

    #       # stage any file changes to be committed
    #       git add version.txt

    #       version=$(head -n 1 version.txt)
    #       # make commit with staged changes
    #       git commit -m "chore: PR for new version $version"

    #       # publish changes
    #       git push origin $branch

    #       # create pull request
    #       gh pr create --base master --head $branch --title "Update version to $version" --body "This PR updates the version to $version"
    #     env:
    #       GH_TOKEN: ${{ secrets.ACTIONS_PAT }}
