name: Post-Update Records and Create Pull Request

on:
  push:
    branches:
      - check-chemont

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  post-update-records:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout this repo's code
        uses: actions/checkout@v4
        with:
          path: MassBank-data

      - name: Checkout MassBank ClassyFire repository
        uses: actions/checkout@v4
        if: ${{ (github.ref != 'refs/heads/main') && (github.base_ref != 'main') }}
        with:
          repository: michaelwenk/MassBank-ClassyFire
          path: MassBank-ClassyFire
          fetch-depth: 1
          ref: main

      - name: Run script to modify the MassBank records
        # working-directory: MassBank-ClassyFire
        run: |
          echo "Running script to modify the MassBank records..."                    

          cd MassBank-ClassyFire
          pip install -r requirements.txt
          echo "Running run.sh ..."
          sh run.sh ../MassBank-data 15

      #   - name: Check for changes
      #     id: check_changes
      #     run: |
      #       if [[ -n "$(git diff --exit-code check-chemont..main)" ]]; then
      #         echo "Changes detected."
      #         echo "has_changes=true" >> $GITHUB_OUTPUT
      #       else
      #         echo "No changes detected."
      #         echo "has_changes=false" >> $GITHUB_OUTPUT
      #       fi

      # Commit and Push Changes if there are any
      - name: Commit and Create Pull Request
        # if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # configure user
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          # create branch name variable
          branch="post-update-records-pull-request"

          # create a new branch for the changes
          git checkout -b $branch

          # stage any file changes to be committed
          git add .

          # make commit with staged changes
          git commit -m "chore: PR with post-updated records"

          # publish changes
          git push origin $branch

          # create pull request
          gh pr create --base main --head $branch --title "Post-Update records" --body "This PR updates the records in case of missing properties, e.g. ChemOnt annotations"
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
