name: Validate the massbank records

on:
  push:
  pull_request:
    branches:
      - 'dev'
      - 'main'


jobs:
  validate:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.6.3
      - name: Checkout massbank-web dev
        uses: actions/checkout@v3
        with:
          repository: MassBank/MassBank-web
          path: .scripts/MassBank-web
          fetch-depth: 1
          ref: dev
        if: ${{ github.ref != 'ref/heads/main' }}
        
      - name: Checkout massbank-web main
        uses: actions/checkout@v3
        with:
          repository: MassBank/MassBank-web
          path: .scripts/MassBank-web
          fetch-depth: 1
          ref: main
        if: ${{ github.ref == 'ref/heads/main' }}

      - name: Build with Maven
        run: mvn -q -f .scripts/MassBank-web/MassBank-Project/MassBank-lib/pom.xml package

      - name: Run the validating script
        run: bash .scripts/run_validation.sh
