name: Validate the massbank records

on:
  push:
  pull_request:
    branches:
      - 'dev'


jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'

      - name: Checkout massbank-web
        uses: actions/checkout@v3
        with:
          repository: MassBank/MassBank-web
          path: .scripts/MassBank-web
          fetch-depth: 1
          ref: dev

      - name: Build with Maven
        run: mvn -q -f .scripts/MassBank-web/MassBank-Project/MassBank-lib/pom.xml package

      - name: Run the validating script
        run: bash .scripts/run_travis.sh