name: Validate the massbank records

on:
  push:
  pull_request:
    branches:
      - 'dev'
      - 'main'


jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Checkout massbank-web dev
        uses: actions/checkout@v3
        with:
          repository: MassBank/MassBank-web
          path: .scripts/MassBank-web
          fetch-depth: 1
          ref: dev
        if: ${{ (github.ref != 'refs/heads/main') && (github.base_ref != 'main') }}

      - name: Checkout massbank-web main
        uses: actions/checkout@v3
        with:
          repository: MassBank/MassBank-web
          path: .scripts/MassBank-web
          fetch-depth: 1
          ref: main
        if: ${{ (github.ref == 'refs/heads/main') || (github.base_ref == 'main') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        working-directory: .scripts/MassBank-web/MassBank-Project
        run: mvn --batch-mode --update-snapshots -f MassBank-lib/pom.xml package

      - name: Run the validating script
        run: bash .scripts/run_validation.sh
